## 
crop_tif:
 _target_ : util.clipRasterByMask
#  DEMPath : None
 vectorMask : C:\Users\abfernan\CrossCanFloodMapping\FloodMappingProjData\HRDTMByAOI\SK_Yorkton_OK\SK_Yorkton_FullBasin.shp
#  outPath : None


# # Add a shp file path to use as a mask for the raster extraction.
mask: 'C:\Users\abfernan\CrossCanFloodMapping\FloodMappingProjData\HRDTMByAOI\SK_Yorkton_OK\SK_Yorkton_FullBasin.shp' # str. Optional defaults to None.
